version: '3.4'

services:
  Project.Recipes.api:
    image: ${DOCKER_REGISTRY-}projectrecipesapi
    build:
      context: .
      dockerfile: Project.Recipes.Api/Dockerfile      

  Project.Recipes.Web:
    image: ${DOCKER_REGISTRY-}projectrecipesweb
    build:
      context: .
      dockerfile: Project.Recipes.Web/Dockerfile
